[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.7", features = ["js"] }
wasm-bindgen = "0.2.82"
